---

name: Differential ShellCheck
on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04

    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@c15070885a82a2c93db8a765d332c38c50dde8b3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
