---

name: Differential ShellCheck
on:
  push:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04

    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@87b655ab4f0356d441e31da1a24dc0ec085beb13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
